# application configuration
logging.level.root: DEBUG

# eureka configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8770}/eureka
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 10
    preferIpAddress: true

# configuration-store configuration
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URL:https://github.com/microservice-foundation/services-configurations-store.git}
          searchPaths:
            - '*service'